### ISSUE TITLE
spacing == 0 issue

### ISSUE THREAD

**Issue by yoris** [wbailey/command_line_reporter#20]
Param spacing  => 0  doesn't work for table (only if param >0 it works ok)

Fixed for myself by adding 
```
if lines != 0
```
to *vertical_spacing* function:

```
  def vertical_spacing(lines = 1)
    puts "\n" * lines if lines != 0
  rescue
    raise ArgumentError
  end
```

**Comment by wbailey** [comment]
I am not seeing the issue with zero that you propose.  For example:

```ruby
2.2.0 :013 > puts "\n" * 0

 => nil
2.2.0 :014 >
```

**Comment by wbailey** [comment]
OK, I get it.  I have pushed an update and tagged 3.3.5 to fix this issue.
