### ISSUE TITLE
.ruby-version should not be in version control

### ISSUE THREAD

**Issue by leoarnold** [wbailey/command_line_reporter#31]
The file `.ruby-version` should not be checked into your Git repo. It might cause Travis CI to run all your commands with the Ruby version specified in `.ruby-version` and therefore ignoring the versions you specified in `.travis.yml`.

For more information, see the [recommended `.gitignore` file](https://www.gitignore.io/api/ruby), especially the section

```
# for a library or gem, you might want to ignore these files since the code is
# intended to run in multiple environments; otherwise, check them in:
# Gemfile.lock
# .ruby-version
# .ruby-gemset
```

**Comment by pboling** [comment]
This recommendation is fully out of date.  All the version locks should be in source control.  Bundler / Rubygems changed the recommendation a few years ago.

This issue should be closed, and if it isn't already, the Gemfile.lock shoudl be _un-ignored_.

**Comment by leoarnold** [comment]
I don't agree. But then again, this issue is 7 years old and I don't even remember it or the gem, so whatever.
